version: '3'
services:
    database:
        container_name: mysql_graphql
        hostname: graphqlmysql
        image: mysql:5.7
        restart: always
        environment:
            - 'MYSQL_ROOT_PASSWORD=123456'
            - 'MYSQL_DATABASE=graphql-mysql-tutorial'
            - 'MYSQL_USER=graphql'
            - 'MYSQL_PASSWORD=123456'
        ports:
          - 3306:3306
        volumes:
            # - mysql_data:/var/lib/mysql
            - ~/.MySQLDBData/mysqlonly/graphql_mysql:/var/lib/mysql
    adminer:
        image: adminer:latest
        restart: always
        ports:
            - 8080:8080
        links:
            - database
volumes:
    mysql_data: {}
# version: '3'
# services:
#   graphql_mysql:
#     container_name: graphql_mysql
#     hostname: graphql_mysql
#     image: mysql
#     restart: always
#     command:
#       # - --default-authentication-plugin=mysql_native_password
#       - --mysql-native-password=ON
#       - --character-set-server=utf8mb4
#       - --collation-server=utf8mb4_unicode_ci
#       - --innodb_force_recovery=0
#     volumes:
#       - ~/.MySQLDBData/mysqlonly/graphql_mysql:/var/lib/mysql
#     ports:
#       - 3306:3306
#     environment:
#       MYSQL_ROOT_PASSWORD: senha
#       MYSQL_DATABASE: graphql_mysql
#       MYSQL_USER: usuario
#       MYSQL_PASSWORD: senha
#       TZ: America/Sao_Paulo